apiVersion: v1
kind: Template
labels:
  template: hello
metadata:
  annotations:
    description: This is an example of application template in OpenShift
    iconClass: default, icon-nodejs
    tags: hello, world
  name: hello-world-template
  namespace:
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: hello-world-service
  spec:
    ports:
    - name: http
      nodePort: 0
      port: ${{SERVICE_PORT}}
      protocol: TCP
      targetPort: ${{INTERNAL_PORT}}
    selector:
      name: hello
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: hello
    name: hello-world-route
  spec:
    host: ${APPLICATION_DOMAIN}
    tls:
      termination: edge
    to:
      kind: Service
      name: hello-world-service
- apiVersion: v1
  apiVersion: v1
  kind: ReplicationController
  metadata:
    name: rc-hello
  spec:
    replicas: 1
    selector:
      name: hello
    template:
      metadata:
        labels:
          name: hello
      spec:
        containers:
        - env:
          - name: MESSAGE
            value: ${GREETING_MESSAGE}
          name: hello
          image: docker.io/kalise/nodejs-web-app:latest
          ports:
          - name: http
            containerPort: ${{INTERNAL_PORT}}
            protocol: TCP
          volumeMounts:
          - mountPath: /var/log
            name: logs
          securityContext:
            privileged: false
            runAsUser: 1001250000
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        volumes:
        - emptyDir: {}
          name: logs
        securityContext:
          fsGroup: 1001250000
parameters:
- description: The exposed hostname that will route to the Hello World service
  name: APPLICATION_DOMAIN
  value: "hello-world.openshift.noverit.com"
  required: true
- description: The internal port used by the pods
  name: INTERNAL_PORT
  value: "8080"
  required: true
- description: The port exposed by the service
  name: SERVICE_PORT
  value: "9000"
  required: true
- description: Greeting message
  name: GREETING_MESSAGE
  value: "Hello OpenShift"
