kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: default-storage-class
  labels:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
parameters:
  resturl: "http://heketi:8080"
