kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: glusterfs
  labels:
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
parameters:
  resturl: "http://heketi:8080"
  volumetype: "replicate:3"
