---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx-svc
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30000
  selector:
    run: nginx
  type: NodePort

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  generation: 1
  labels:
    run: nginx
  name: nginx-github
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
          name: "http-server"
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html
          readOnly: true
      volumes:
      - name: html
        gitRepo:
          repository: https://github.com/noverit/docker-lab-slides.git
          revision: master
          directory: .
      dnsPolicy: ClusterFirst
      restartPolicy: Always
