apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: content-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    kubernetes.io/hostname: kuben05
  volumes:
  - name: content-data
    hostPath:
      path: /data/nginx/html
