---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apache-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: glusterfs-storage-class
