---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-share-01
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: "share01"
