---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-share-00
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: "share-00"
