---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share02
  labels:
    name: share02
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/data_storage/kubernetes/share-02"
    server: centos
  persistentVolumeReclaimPolicy: Recycle
