apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readonly-filesystem
  namespace:
  labels:
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["/bin/sleep", "3600"]
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: myvolume
      mountPath: /volume
      readOnly: false
  volumes:
  - name: myvolume
    emptyDir:
